[package]
name = "dsa"
version = "0.1.0"
edition = "2024"
authors = ["Huseen Munye <>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/hmunye/dsa"
description = """
Data Structures & Algorithms
"""
categories = []
keywords = []

[dependencies]
